image: python:3.11-bookworm

pages:
  script:
    - |
      apt-get update && \
        export DEBIAN_FRONTEND=noninteractive && \
        apt-get -y install --no-install-recommends \
      python3-brotli \
      python3-cffi \
      python3-pip \
      zip
    - pip install poetry==1.5.1
    - poetry config virtualenvs.in-project true
    - poetry install --no-root
    - poetry run mkdocs build -d public

  artifacts:
    paths:
      - public
  only:
    - main
