#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

export SELECT_WEEK="999"
export SHOW_SOLUTION="999"

mode="serve"
while getopts "bw:s:" opt; do
    case ${opt} in
    b)
        mode="build"
        ;;
    w)
        SELECT_WEEK=$OPTARG
        ;;
    s)
        SHOW_SOLUTION=$OPTARG
        ;;
    \?)
        echo "Usage: serve [-b] [-w week] [-s solution]" 1>&2
        exit 1
        ;;
    :)
        echo "Invalid option: $OPTARG requires an argument" 1>&2
        exit 2
        ;;
    esac
done

if [ $mode = "build" ]; then
    # Build MkDocs
    mkdocs build -f config/mkdocs.yml
else
    # Serve MkDocs
    mkdocs serve -f config/mkdocs.yml
fi